### ISSUE TITLE
Feature: autocraft (Hammers etc.)

### ISSUE THREAD

**Issue by ghost** [minetest-mods/workbench#3]
Hi.

It would be great if 
1) hammers in the storage would automatically be taken when repairing tools and when a hammer breaks.
2) it would be awesome if the crafting table would be specific to that workbench and it would automatically craft the object by taking components it needs in the storage. Example it would allow to put the hammer recipe and sticks + steel ingots in the storage and it would just build hammers until the storage is full or when it misses a component.

Thanks for your awesome work.

**Comment by kilbith** [comment]
What you are wanting is the mod [technic](https://github.com/minetest-technic/technic) or [pipeworks](https://github.com/minetest-mods/pipeworks). I don't like when the game becomes too "assisted" / automated, too easy in the end.

Have fun !
