### ISSUE TITLE
Unrealistic and possible repair style change?

### ISSUE THREAD

**Issue by Taose** [minetest-mods/workbench#4]
I tried repairing a wooden weapon, yes, sue me. Yet it wore out the steel hammer faster than it took to repair the weapon and it also took forever to do it. 

Would it instead be better not to have the hammer decrease so rapidly and have the tool/weapon repair faster? Assuming that you can get the "additional" material that you would need? 

For example, to repair a wooden axe, you would need one chunk of wooden planks and 6 uses of hammer to repair fully. Maybe a stick too?

**Comment by kilbith** [comment]
You can tweak the repair / wearing values here : https://github.com/minetest-mods/workbench/blob/master/init.lua#L184-L186

I've never been sure whether these values are right, gameplay wise. Feedbacks like yours help though.

Please also consider opening issues about the workbench on the [xdecor repository](https://github.com/minetest-mods/xdecor) instead.
