### ISSUE TITLE
More hammers varying efficiencies

### ISSUE THREAD

**Issue by Taose** [minetest-mods/workbench#5]
Quite simply, the recipe for creating a hammer could be varied and the hammers usages could also be varied. 

Instead of just a steel hammer, there could also be a wooden mallet 

wood | stick | wood
empty | stick | empty
empty | empy | empty

This would make it easier to repair weapons at earlier stages too.

**Comment by kilbith** [comment]
The recipe for the steel hammer is unlikely to change but I could consider adding a wooden mallet.

**Comment by Taose** [comment]
and a bronze, mese and diamond?

**Comment by kilbith** [comment]
No, sorry. I won't clutter the inventory with all kinds of hammers.

**Comment by Taose** [comment]
Never mind, I'll get what I want another way. Thank you.
